DROP TABLE IF EXISTS Sales.OrderLines;
DROP TABLE IF EXISTS Sales.Orders;
DROP TABLE IF EXISTS Sales.Employees;
DROP TABLE IF EXISTS Warehouse.Shipment;
DROP TABLE IF EXISTS Product;
DROP TABLE IF EXISTS Product.ProductType;
DROP TABLE IF EXISTS Users.Member;
