IF OBJECT_ID(N'Users.Member') IS NULL
BEGIN
	CREATE TABLE Users.Member
	(
	    MemberID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
		Email NVARCHAR(128) NOT NULL,
		FirstName NVARCHAR(32) NOT NULL,
		LastName NVARCHAR(32) NOT NULL,
		Phone NVARCHAR(32) NOT NULL,
		BillingAddress NVARCHAR(128) NOT NULL,
		Points INT NOT NULL,
		JoinedOn DATETIMEOFFSET NOT NULL DEFAULT(SYSDATETIMEOFFSET()),
		BirthDate DATETIMEOFFSET NOT NULL DEFAULT(SYSDATETIMEOFFSET()),
		[Status] NVARCHAR(32) NOT NULL,

		CONSTRAINT [PK_Users_Member_MemberID] PRIMARY KEY CLUSTERED
		(
			MemberID ASC
		)

		CONSTRAINT [UK_Users_Member_Phone] PRIMARY KEY CLUSTERED
		(
			Email,
		    Phone  
		)
	);
END