BEGIN
	CREATE TABLE Sales.Orders
	(
		ShipmentID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
		ShipmentDate DATETIMEOFFSET NOT NULL DEFAULT(SYSDATETIMEOFFSET()),
		ShipmentAddress NVARCHAR(128) NOT NULL DEFAULT(SYSDATETIMEOFFSET())
);
END