IF OBJECT_ID(N'Warehouse.Shipment') IS NULL
BEGIN
	CREATE TABLE Warehouse.Shipment
	(
		ShipmentID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
		ShipmentDate DATETIMEOFFSET NOT NULL DEFAULT(SYSDATETIMEOFFSET()),
		ShipmentAddress NVARCHAR(128) NOT NULL DEFAULT(SYSDATETIMEOFFSET())

		CONSTRAINT [PK_Warehouse_Shipment_ShipmentID] PRIMARY KEY CLUSTERED
      (
         ShipmentID ASC
      )
);
END